-- LdbcQuery2 — Top-20 recent messages by direct friends (before maxDate).
-- Hybrid: 1 Cypher call (friend-set via single-hop KNOWS) + outer SQL LATERAL on the
-- MessageByCreator side table for top-N per friend, then global top-20.
--
-- Same shape as IC9 (Phase C): drive top-N by creator from the (creator_business_id,
-- creation_date DESC, message_business_id) composite index on MessageByCreator,
-- LATERAL LIMIT 20 per friend to avoid scanning all friend-messages before global sort.
--
-- Measured 2026-05-15 SF3: 145-238× mean speedup (~193× across 5 sample personIds)
-- vs the prior 2-arm Comment+Post UNION shape that scanned ~62K Comment vertices per
-- call to apply the date filter post-fetch. Byte-identical output on all 5 samples.
--
-- §14 compliance: outer SQL only touches the non-AGE MessageByCreator side
-- table. Friend names (personFirstName, personLastName) are projected from
-- the Cypher RETURN (Phase A: PersonSide retired). No AGE label table reads
-- in outer SQL.
--
-- Date filter: `<= $maxDate` (NOT `<`) matches the Neo4j reference (cypher/queries/
-- interactive-complex-2.cypher line 9: `message.creationDate <= $maxDate`). The LDBC
-- v1 oracle was generated by the Neo4j reference, so `<=` is the byte-correct operator
-- here even though AGENTS.md's "How to Review a Query" §3 generic guidance says "<".
--
-- messageContent is kept as agtype (NOT cast to ::text). AgeConverter.toStr unwraps
-- the outer JSON quotes of an agtype string before any trim, preserving content's
-- internal trailing whitespace (LDBC datagen produces messages with significant
-- trailing chars). A ::text cast bypasses the unwrap and triggers .trim() on
-- the bare value, stripping the trailing space and breaking validation.
--
-- Parameterized-path note: $maxDate is projected back out of the friend-set
-- Cypher call (as "md") rather than referenced as bare outer SQL. The driver's
-- parameterized handler only binds the agtype-JSON parameter map into AGE
-- Cypher invocations; any $name in outer SQL reaches Postgres unsubstituted
-- and trips "syntax error at or near $". Same agtype payload is reused per
-- row — no extra invocation, no extra binding, no per-row overhead at plan
-- time (the LATERAL sees friends.max_date as a row-local constant and can
-- still range-scan idx_msgbycreator_creator_date_msg).
-- AGE-QUIRKS §13 reminder: the literal token "cy" + "pher(" must never appear
-- in SQL comments here, because AgeListOperationHandler.countCypherCalls
-- substring-scans the whole template (including comments) and would over-bind.

WITH friends AS (
  SELECT
    (fid::text)::bigint AS person_id,
    (md::text)::bigint  AS max_date,
    fn::text            AS first_name,
    ln::text            AS last_name
  FROM cypher('$graphName', $$
    MATCH (p:Person {id: $personId})-[:KNOWS]->(friend:Person)
    RETURN friend.id AS fid, $maxDate AS md, friend.firstName AS fn, friend.lastName AS ln
  $$) AS x(fid agtype, md agtype, fn agtype, ln agtype)
)
SELECT
  m.creator_business_id::ag_catalog.agtype        AS personId,
  ag_catalog.text_to_agtype(friends.first_name)   AS personFirstName,
  ag_catalog.text_to_agtype(friends.last_name)    AS personLastName,
  m.message_business_id::ag_catalog.agtype        AS messageId,
  ag_catalog.text_to_agtype(m.content)            AS messageContent,
  m.creation_date::ag_catalog.agtype              AS messageCreationDate
FROM friends
CROSS JOIN LATERAL (
  SELECT mm.creator_business_id, mm.message_business_id, mm.creation_date, mm.content
  FROM ldbc_snb."MessageByCreator" mm
  WHERE mm.creator_business_id = friends.person_id
    AND mm.creation_date <= friends.max_date
  ORDER BY mm.creation_date DESC, mm.message_business_id ASC
  LIMIT 20
) m
ORDER BY m.creation_date DESC, m.message_business_id ASC
LIMIT 20;
