database=org.ldbcouncil.snb.impls.workloads.age.interactive.AgeInteractiveDb
workload=org.ldbcouncil.snb.impls.workloads.interactive.LdbcSnbInteractiveWorkload

queryDir=queries

age_endpoint=jdbc:postgresql://localhost:5432/ldbcsnb
age_user=postgres
age_password=admin123
age_graph_name=ldbc_snb

thread_count=4
operation_count=1000000
warmup_count=100000
time_compression_ratio=1.0
status_interval=30

ldbc_snb_interactive_parameters_dir=test-data/substitution_parameters
ldbc_snb_interactive_update_stream_dir=test-data/updateStream
ldbc.snb.interactive.short_read_dissipation=0.2

printQueryNames=false
printQueryStrings=false
printQueryResults=false
