database=org.ldbcouncil.snb.impls.workloads.age.interactive.AgeInteractiveDb
workload=org.ldbcouncil.snb.impls.workloads.interactive.LdbcSnbInteractiveWorkload

queryDir=queries

age_endpoint=jdbc:postgresql://localhost:5432/ldbcsnb
age_user=postgres
age_password=admin123
age_graph_name=ldbc_snb

mode=validate_database
thread_count=1
operation_count=10000

validation_params_file=test-data/validation_params.csv

# AGE does not support shortestPath/allShortestPaths
LdbcQuery13.enable=false
LdbcQuery14.enable=false

printQueryNames=false
printQueryStrings=false
printQueryResults=false
